-- vim.cmd([[hi LineNr guibg=NONE]])
vim.cmd([[hi WinBar guibg=StatusLine guifg=WildMenu]])
vim.cmd([[hi WinBarNC guibg=StatusLineNC guifg=WildMenu]])
-- vim.cmd([[hi CursorLine guibg=#121212]])
-- vim.cmd([[hi CursorLineNr guibg=#121212]])
-- vim.cmd([[hi StatusLine guibg=#000000]])
-- vim.cmd([[hi Normal guibg=NONE]])
-- vim.cmd([[hi Normal ctermbg=NONE]])
